### PR TITLE
upgrade webpack 5 and bootstrap 5 to address outdated/vulnerable dependencies

### PR DESCRIPTION
**Pull request by sio4**
Upgraded to Webpack 5 and Bootstrap 5 to address outdated (or deprecated) or vulnerable dependencies.

- This PR covers issue #26
- Obsoletes issue #22 (and #25).
- Also, this PR partially covers issue #7 but I wish we keep jQuery to be installed by default. (I believe jQuery is still one of the most famous javascript libraries for web developers)
- as a side work, it fixed the routes table bug of the default index.

### CODE REVIEW

**Review by paganotoni — APPROVED** [review]

**Comment by matthew-graves** [comment]
Hi mike-lloyd03,

I just pulled down the latest cli from source and the "buffalo new" command works as expected (I am also having your same issue when pulling the latest via go install). There just needs to be a new release done to get this patch down to everyone. The latest release, v0.17.2 was done on Sept 1, but this fix was merged in on Sept 7.

**Comment by paganotoni** [comment]
FYI v0.17.5 released 
cc @mike-lloyd03 @matthew-graves

**Comment by mike-lloyd03** [comment]
Confirmed fixed on MacOS with version 0.17.5. I will test on Linux later and report back.

**Comment by matthew-graves** [comment]
I pulled it down and confirmed it's working as expected on Linux. Thank you @paganotoni !

**Comment by paganotoni** [comment]
Credits to @sio4 for the PR! Great to see its working well.

**Pull request merged**
