### PR TITLE
Hide embed.go from embedded file systems

### PR DESCRIPTION
**Pull request by fasmat**
This ensures that the code for embedding is not embedded itself.

### CODE REVIEW

**Comment by fasmat** [comment]
@sio4 @paganotoni This prevents embed.go from showing up in the embedded file systems.

Since this is A LOT of repeated code, maybe shadowFS should be part of the `gobuffalo/buffalo` module? It can also easily be adapted to hide any file if needed.

**Comment by sio4** [comment]
My opinion is that it should be a submodule of gobuffalo/buffalo or be a separated universal one like packd.

It could have hiding feature, but my opinion is that the most important feature we need regarding file embedding is supporting live files on the the real disk (for dev status and/or for overriding).

**Comment by fasmat** [comment]
@sio4 embedded file systems are updated upon a rebuild. If we want proper hot reloading we would need to use `os.DirFS("path")` over `embed.FS` at least when using buffalo dev. This would mean that the generated files should use os.DirFS over embed.FS and when building the embed.go files are replaced with embed.FS

At the moment something similar is done with `main.go`. The status in your repository is the main.go for development. When you build your application with `buffalo build` it is overwritten with a new `main.go`.

**Comment by fasmat** [comment]
@sio4 The more I think about it the clearer it is to me that shadowFS should go into `gobuffalo/buffalo` and decide based on circumstance (e.g. is a `.buffalo.dev.yml` file present) if it should use a `os.DirFS` or `embed.FS`.

I'll update this PR and create a new one in `gobuffalo/buffalo`.

**Comment by paganotoni** [comment]
Yes, I think making it a package in gobuffalo/buffalo would be ok as we will keep the dependency direction being the same (cli->buffalo)

**Comment by paganotoni** [comment]
@fasmat just to be clear, this PR does not fix our issue with templates and hot reloading, right?

**Review by paganotoni — APPROVED** [review]
This looks good. I agree with you we should create a package that holds this. In the sake of simplicity I would suggest adding that package to gobuffalo/buffalo.

**Comment by fasmat** [comment]
> @fasmat just to be clear, this PR does not fix our issue with templates and hot reloading, right?

yes, it only hides embed.go. I'm working on making hot reload work.

**Comment by paganotoni** [comment]
Awesome. Thanks!

**Pull request merged**
