### PR TITLE
Bump go version to 1.18

### PR DESCRIPTION
**Pull request by john-s-morgan**

### CODE REVIEW

**Comment by john-s-morgan** [comment]
This moves the dockerfile versions forward to support [go 1.18](https://go.dev/blog/go1.18).

**Comment by fasmat** [comment]
Hi @john-s-morgan! Thanks for the contribution, but before we can upgrade our Dockerfiles we should make sure that our pipeline and code is also updated to 1.18 and we've dropped support for 1.16.

**Comment by john-s-morgan** [comment]
> Hi @john-s-morgan! Thanks for the contribution, but before we can upgrade our Dockerfiles we should make sure that our pipeline and code is also updated to 1.18 and we've dropped support for 1.16.

I can appreciate that. Other than uploading the workflow yaml files, is there anything I can do to help with that?

**Comment by fasmat** [comment]
I'm not expecting many necessary changes on the buffalo codebase besides updating the yaml files in the pipeline, but I remember a few todos in our codebase with 1.16 specific code that should be cleaned up when we now drop support for it.

**Comment by sio4** [comment]
Thank you for your patience @john-s-morgan.

We are working on shifting the supported go version. However, I could not merge your commit directly from your fork since there were some conflict changes during the period. Sorry for that!

I appreciate your support and this PR, and I hope you can enjoy the buffalo with the go1.18 soon!

**Pull request closed without merging**
